spring.application.name=backend

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3307/stockflow?useTimezone=true&serverTimezone=UTC&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jdbc.template.max-rows=500
logging.level.org.springframework.jdbc.core.JdpiobcTemplate=DEBUG