spring.application.name=backend
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:stockflow}?useTimezone=true&serverTimezone=UTC&characterEncoding=UTF-8
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.username=${DB_USERNAME:root}
