name: build.yml
on:
  pull_request:
    branches:
      - main
    types:
      - closed
jobs:
  build-and-push:
    if: github.event.pull_request.merged == true

    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: pezao-sound-api

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4


      - name: Buscando cache das dependências Maven
        uses: actions/cache@v5
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Baixando as dependências Maven
        run: mvn dependency:go-offline

      - name: Build do .jar
        run: mvn clean package -Pprod -DskipTests

      - name: Docker metadata para a tag
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=sha

      - name: Autenticando no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build da imagem e envio ao repositório
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}

